#!/usr/bin/env bash

source $(dirname $0)/helpers.sh
LOG=/tmp/log/$(basename $0).log
mkdir -p /tmp/log

USER=vagrant

(
  display Starting build at $(date)

  display Datastax Getting Started Instructions
  (
    echo "deb http://kenneth_mashape.com:abmNzOTPpEFukez@debian.datastax.com/enterprise stable main" | tee -a /etc/apt/sources.list.d/datastax.sources.list
    curl -L https://debian.datastax.com/debian/repo_key | apt-key add -
    apt-get update
  ) 2>&1 | indent

  display Install Datastax packages
  (
    xargs apt-get install -y < $(dirname $0)/packages.txt
  ) 2>&1 | indent

  display Clean Up
  (
    rm -rf /var/lib/apt/lists/*
  ) 2>&1 | indent

) 2>&1 | tee $LOG

display "Ready to go!"
